set_project("audio_buffer")
set_license("GPL-3.0")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "$(buildir)"})
set_policy("check.auto_map_flags",true)
set_policy("build.warning",true)
set_warnings("all","extra")
add_requires("ffmpeg")
target("audio_buffer")
set_kind("static")
add_files("**/*.c")
add_packages("ffmpeg")
add_includedirs("include",{public = true})
target_end()