add_requires("xaudio2redist")
target("example_xaudio2")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "$(buildir)"})
set_policy("check.auto_map_flags",true)
set_policy("build.warning",true)
set_warnings("all","extra")
set_kind("binary")
set_languages("c++14")
add_deps("audio_buffer")
add_files("main.cpp")
add_packages("xaudio2redist")
target_end()